[workspace]
resolver = "2"
members = [
    "bigworlds",
    "bigworlds-cli",
    "clients/grpc-client",
    "examples/*/viewers/*",
    # "examples/**"
]

exclude = [
    "examples/cubes/services/rapier",
    "examples/cubes/behaviors/setup",
    "examples/cubes/viewers/bevy",
]
